
spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.27.240.112/lianjia?serverTimezone=Asia/Shanghai
    username: root
    password: a110791
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  port: 8081
#  servlet:
#    context-path: "/springboot"

#引入映射文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf



